version: '3.3'
services:
  d3m:
    build: .
    container_name: d3m-analytics
    stdin_open: true
    tty: true
    env_file:
    - .env
    entrypoint: /bin/bash
    volumes:
      - ${DATA_ROOT}:${DATA_ROOT}
